[workspace]
  members = ["wen-core", "wen-contrib"]
  build-members = []
  test-members = []
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  target-dir = ""
  script-dir = ""

[dependencies]
